### PR TITLE
Attestation for nc22.0 from mjgill89

### PR DESCRIPTION
**Pull request by mjgill89**
Attestation for nc22.0 from mjgill89

### CODE REVIEW

**Comment by JeremyRand** [comment]
Could you upload your OpenPGP pubkey to hkps://keys.openpgp.org so that the instructions at https://github.com/namecoin/namecoin-core/tree/master/contrib/builder-keys work?

**Comment by mjgill89** [comment]
@JeremyRand it should be there now.

**Comment by JeremyRand** [comment]
Hmm, I get `BAD signature` when I run `gpg --verify` on the signature file.  Is it possible that the signature didn't get updated when you added some extra hashes?

Also, can you squash the 2 commits, so that we don't have the nc23.0 files being added and then immediately deleted?

**Comment by JeremyRand** [comment]
ACK c84e8305c5d74c1df37cbf13d11e9af8e1fd26c4

**Comment by mjgill89** [comment]
the correct signature was found 🥇

**Pull request merged**
