### PR TITLE
attestation of mjgill89 for nc22.0 and nc23.0

### PR DESCRIPTION
**Pull request by mjgill89**
it seems my guix-build had issues and only a subset of things were built. Jeremy seems to have lots 🥇 so I will try to build similarly but here's what I have so far.

### CODE REVIEW

**Comment by mjgill89** [comment]
Unfortunately I have run into another issue which seems the same as [this](https://github.com/firoorg/firo/issues/1150). Only 17 of the 20 hashes are in my attestation :(

**Comment by mjgill89** [comment]
I don't seem to have had issues 🤞 with hashes for the 23.0 release. I did not change the folder structure from what guix created which doesn't match the previous nc22.0 structure but o well?

**Comment by JeremyRand** [comment]
Nice, thanks for contributing these!  Could you please split the 22.0 and 23.0 attestations into distinct PR's?  That'll make it easier to review+merge.

**Comment by JeremyRand** [comment]
> I did not change the folder structure from what guix created which doesn't match the previous nc22.0 structure but o well?

That's expected; I fixed a bug between 22.0 and 23.0, and that bugfix causes the 23.0 folder structure to look like what Bitcoin Core has, as intended.  All future tags will look like 23.0 does.

**Comment by mjgill89** [comment]
made 2 new prs

**Pull request closed without merging**
